### ISSUE TITLE
question about visual attention map

### ISSUE THREAD

**Issue by Ellyuca** [fawazsammani/nlxgpt#2]
Hi @fawazsammani.

First of all thank you once again for providing the tutorial for single image usage.

I was playing around with the model and I am curious about one thing.
Together with the textual explanation, we can also have the visual attention explanation with the attention map.
So, I was wondering if this visual explanation is computed considering the entire sentence output (= answer + explanation). 
It is possible to divide the visual attention map in due different images: one that focuses on the classification part (answer) and another one that focuses on the explanation part. So in the first one I will have highlighted areas that are important for the answer prediction and in the second one it will be shown only the most important parts for explanations only.

Sorry for my lack of knowledge regarding this problem.
Thank you for your time.
Best wishes.

**Comment by Ellyuca** [comment]
After analyzing a bit more the code I think I understand where the inconsistency between the attention maps shape and number of words comes from. Just my two cents, so please correct me if I am wrong.

It seems like the model returns an attention map for each token generated, so basically the shape of the attention tensor is consistent with the number of tokens in `input_ids`. After the generation of tokens finishes, `inputs_ids` has the following structure:  `inputs_ids` = _endoftext the answer is answer because explanation_ , and then only the part in `current_output `= _answer because explanation_ is being decoded and returned. Given the type of tokenizer used, complex/rare words are represented by multiple tokens (like for example ballroom = Ġball + room, skis = Ġsk + is). So during the decoding phase more tokens will be used to return complex words, so the number of words in the final sentence can be different from the number of tokens. Hence the difference in shape size.

Therefore, iterating over the `last_am = xa_maps[-1].mean(1)[0, question_len:]`, will give me the **visual explanation for all tokens** (which @fawazsammani  kindly explained already), but we don't always have a 1-to-1 relantionship between tokens and words, since more complex words are composed from multiple tokens (which was the part that I missed). 

Moreover, for the ACT_X visual explanation output, I think the attention maps of the  _endoftext the answer is_ part should be excluded in order to start from the attention map of the _answer_, like in the case of VQA_X.
So maybe doing something like this (@fawazsammani  what do you think? Is this correct?):

`input_len = len(tokenizer.convert_ids_to_tokens(input_ids[0]))`
`last_am = xa_maps[-1].mean(1)[0, input_len:]`
and then iterate over `last_am` to get the visual explanations for  all tokens of the _answer because explanation_ part.

In the case of complex words, how do we manage/interpret the visual explanation? If I take the example with "ballroom" I will have one visual map for the "ball" word and one for the "room", which separately don't really have he same meaning of ballroom. Room is more similar with ballroom, but ball doesn't quite fit the meaning here.

@fawazsammani  What is your opinion on this?

Thank you.
Sorry once again for the long post.
Have a great day.

**Comment by fawazsammani** [comment]
Hi @Ellyuca 
Thank you for taking the time to write your question and understanding the code. I will reply you tonight. 

Regards

**Comment by fawazsammani** [comment]
Hi again @Ellyuca 

> Therefore, iterating over the last_am = xa_maps[-1].mean(1)[0, question_len:], will give me the visual explanation for all tokens (which @fawazsammani kindly explained already), but we don't always have a 1-to-1 relationship between tokens and words, since more complex words are composed from multiple tokens (which was the part that I missed).

Yes that's correct. This will give you the cross-attention maps for the byte-pair encoded words. This in turn comes from the tokenized words. 

> In the case of complex words, how do we manage/interpret the visual explanation? If I take the example with "ballroom" I will have one visual map for the "ball" word and one for the "room", which separately don't really have he same meaning as ballroom. Room is more similar with ballroom, but ball doesn't quite fit the meaning here.

In that case, you can choose to average them together, or make your life simple and choose one of them. They usually should portray the same thing (if not then they should be somehow similar). Taking your example, when the model generates "ball", it knows that the next word to be generated is "room" (its already trained). So the visual attention map will already correspond to "room" or in general "ballroom". Maybe i'm wrong on this. I'm not exactly sure if this thing is discussed in the literature. Usually people just ignore it. 

> Moreover, for the ACT_X visual explanation output, I think the attention maps of the "endoftext the answer is" part should be excluded in order to start from the attention map of the "answer", like in the case of VQA_X.
> So maybe doing something like this (@fawazsammani what do you think? Is this correct?):

Yes! You are correct. This is a small mistake in the code that I did not pay attention to. Thanks a lot for pointing this out. But to verify point 2 above, you can see that the visual attention maps for "the" (since we are taking the first index of xa_maps) already corresponds to the correct answer, even though the answer is not yet generated. That verifies the fact that the model already knows future words. 

Finally, if you are looking into model explainability, you shouldn't really trust attention maps that much. In some cases, they are very noisy and don't even correspond to "why" the model made such as decision. Instead, you may look at explainable ai techniques such as Grad-CAM, Integrated Gradients, Saliency Methods, Occlusion, LIME...etc. The [captum](https://captum.ai/) library offers an efficient and easy way to run them. 

Please let me know if you have any other questions. 

Regards
Fawaz

**Comment by Ellyuca** [comment]
Hi @fawazsammani.
Thank you for taking time to answer my questions. It really helped clarifying some of my doubts.
Just a few final thoughts on this discussion.

> Finally, if you are looking into model explainability, you shouldn't really trust attention maps that much. In some cases, they are very noisy and don't even correspond to "why" the model made such as decision.

Looking at some examples, the attention maps are indeed very noisy and don''t make much sense sometimes.
Basically, I wanted to see what was the relationship between the generated words and the most highlighted parts of the attention map and if this relationship is somehow aligned with a human understanding/judgement.

For example, given the image 017829326.jpg (a woman playing the violin), for ACT_X we get the following output: _violin because she is sitting in a chair holding a violin in her hands_. 
![original_violin](https://user-images.githubusercontent.com/9151725/182825354-68905642-f38b-4334-9193-5f63118b9f66.jpg)

It seems like the attention map at index 0 (_endoftext_) focuses on parts such as the face/neck, the violin, which makes sense to the predicted answer. Same for the index 3 (_is_) where the attention is mostly on the violin part. But then when we move to index 4 (_violin_) the most highlighted areas is the neck of the woman and a corner of the violin case. I would except the attention map index 4 (_violin_) to be more like the one of the index 3 or even index 0.
![attn_map_224x224x3_index_0](https://user-images.githubusercontent.com/9151725/182830946-e3f1ae26-bfbb-4676-94c9-cc0e67e230d1.png)

Analyzing other examples as well, it seems that the first attention map (index 0) points to the parts of the image used for the generation of the entire sentence. It looks like a sort of "summary" of the output, as you also mentioned something similar above:

> you can see that the visual attention maps for "the" (since we are taking the first index of xa_maps) already corresponds to the correct answer, even though the answer is not yet generated.

Sometimes, there is a matching  between the attention map and it's corresponding token, in the sense that the attention map points to the area in the image where that exact object/attribute/etc can be found. But for most of the examples I analyzed this is not the case. So I agree with you on this:

> don't even correspond to "why" the model made such as decision

Thank you once again for all your patience and time.
Best wishes.

**Comment by fawazsammani** [comment]
@Ellyuca Yes exactly. Attention maps are a very bad way of explaining model decisions. Why they are still widely used is because they are model-intrinsic. They come naturally with the model so people don't have to implement these post-hoc techniques to explain their model. But actually many papers show that attention maps are meaningless and should not be taken too seriously. But again, they may work very well in some cases. 

I would like to thank you for the time you spent in understanding this code and every piece of it (probably you now understand it more than I do, and if I forgot what I wrote then I can revert back to you :). And thank you also for the mistake you figured out.

If you have other questions (not only on this code, but anything related general), please reach out to me via email: fawaz.sammani@vub.be

Have a great day!
