### ISSUE TITLE
'prepare_data' folder and README incomplete

### ISSUE THREAD

**Issue by katelyn98** [fawazsammani/nlxgpt#8]
Hi, I was hoping to use this model to explain predictions for a different task than used in the paper which will require me to prepare explanations myself as well. It seems that the prepare_data folder that is referenced in the explain_predict folder is empty though. Will there be instructions coming soon for the specific steps the authors did for this process? Thanks!

**Comment by fawazsammani** [comment]
Hello @katelyn98 ,
For some reason I forgot to upload them, and didn't notice that.
I will upload them today after a few hours. Thanks a lot :)

**Comment by fawazsammani** [comment]
Hi again @katelyn98 
[here](https://github.com/fawazsammani/nlxgpt/tree/main/utils) i uploaded two notebook files. [nle_preprocess](https://github.com/fawazsammani/nlxgpt/blob/main/utils/nle_preprocess.ipynb) is the script to process the natural language explanations data from their source, and [preprocess_for_cococaption_eval](https://github.com/fawazsammani/nlxgpt/blob/main/utils/preprocess_for_cococaption_eval.ipynb) is to convert the natural language explanations data from the source to the format the cococaption expects for evaluation. The source data can be downloaded from the respective dataset website (e.g. VQA-X from [VQA](https://visualqa.org/)) but i don't think they will help you since you said that your data is different...

If you have other questions, please let me know :) 

Regards
Fawaz

**Comment by katelyn98** [comment]
Hi @fawazsammani 
Thanks for getting to this issue so quickly! This notebook is great. Thank you so much for sharing that!
All the best,
Katelyn
